env:
  browser: true
  node: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - react
  - import
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
globals:
  Atomics: readonly
  React: writable
  SharedArrayBuffer: readonly
settings:
  react:
    version: detect
rules:
  # NextJs does not require you to import React into each component.
  # so suppress errors for missing 'import React' in files.
  react/react-in-jsx-scope:
    - off
  react/prop-types: # We use TypeScript rather than React.propsType
    - off
  require-await:
    - error
  brace-style:
    - warn
    - 1tbs
  curly:
    - warn
    - all
  dot-location:
    - warn
    - property
  dot-notation:
    - warn
  eqeqeq:
    - warn
    - smart
  indent:
    - off
  "@typescript-eslint/indent":
    - warn
    - 4
  linebreak-style:
    - off
  no-console:
    - warn
  no-trailing-spaces:
    - warn
  no-else-return:
    - error
  no-implicit-coercion:
    - error
  no-multi-spaces:
    - warn
    - {
      ignoreEOLComments: true
    }
  no-return-await:
    - error
  wrap-iife:
    - error
    - inside
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  yoda:
    - warn
    - never
  block-spacing:
    - warn
    - always
  camelcase:
    - warn
    - {
      properties: always,
      ignoreDestructuring: false,
      allow: []
    }
  comma-dangle:
    - warn
    - never
  comma-spacing:
    - warn
    - {
      before: false,
      after: true
    }
  comma-style:
    - warn
    - last
  eol-last:
    - warn
    - always
  func-call-spacing:
    - warn
    - never
  jsx-quotes:
    - warn
    - prefer-double
  key-spacing:
    - warn
    - {
      beforeColon: false,
      afterColon: true,
      align: value
    }
  keyword-spacing:
    - warn
    - {
      before: true,
      after: true
    }
  new-parens:
    - warn
    - always
  no-lonely-if:
    - warn
  no-whitespace-before-property:
    - warn
  object-curly-spacing:
    - warn
    - always
  array-bracket-spacing:
    - warn
    - never
  space-before-blocks:
    - warn
    - always
  space-before-function-paren:
    - warn
    - {
      anonymous: always,
      named: never,
      asyncArrow: always
    }
  space-in-parens:
    - warn
    - never
  spaced-comment:
    - warn
    - always
  switch-colon-spacing:
    - warn
    - {
      before: false,
      after: true
    }
  template-tag-spacing:
    - warn
    - never
  unicode-bom:
    - warn
    - never
  wrap-regex:
    - warn
  import/order:
    - warn
