language: node_js
node_js:
  - 12
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - $NOTIFICATION_WEBHOOK
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
